services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ohome-server
    environment:
      GIN_MODE: release
      PORT: 18090
    volumes:
      - /opt/ohome/conf/config.yaml:/app/conf/config.yaml:ro
      - /opt/ohome/data:/app/data
      - /opt/ohome/log:/app/log
    ports:
      - "18090:18090"
    restart: unless-stopped
