services:
  server:
    image: ${OHOME_RUNTIME_IMAGE:-hanlinwang0606/ohome:runtime-v2026.03.1}
    container_name: ohome-server
    environment:
      GIN_MODE: release
      PORT: 18090
    volumes:
      - /opt/ohome/conf:/app/conf
      - /opt/ohome/data:/app/data
      - /opt/ohome/log:/app/log
    ports:
      - "18090:18090"
    restart: unless-stopped
